src/components/Popup/Popup.styled.tsx
src/pages/Main/Achievements/AchievementBox.styles.ts
src/pages/Main/Achievements/AchievementBox.tsx
src/pages/Main/Achievements/Achievements.styles.ts
src/pages/Main/Achievements/Achievements.tsx
src/pages/Main/BottomInfo/BottomInfo.styles.ts
src/pages/Main/BottomInfo/BottomInfo.tsx
src/pages/Main/FarmSyetemNav/FarmSystemNav.styled.ts

> #40 
> 1. 사진 움직이는 속도 빠르게 하기.
> 2. 성과 숫자 박스 올라가는 애니메이션 추가
> 3. 여러 디테일 수정

[FIx] 성과 및 바닥 정보 업데이트 

---

src/pages/Main/Achievements/AchievementItem.styles.ts
src/pages/Main/BottomInfo/BottomInfo.tsx
src/pages/Main/Intro/Intro.tsx
src/pages/Main/index.styled.tsx

> #50 
> 남은 작업 완료~ + 인트로 모바일 뷰에 id추가완료

#Fix QA 발견사항 수정 

---

src/pages/FAQ/Frame.styled.ts
src/pages/FAQ/Frame.tsx
src/pages/FAQ/Question.styled.ts
src/pages/FAQ/Question.tsx
src/pages/FAQ/index.styled.ts
src/pages/FAQ/index.tsx

> ex) #64 
> FAQ 반응형 수정 
웹 뷰
https://github.com/user-attachments/assets/5431201c-e2ab-4d46-b644-e9392c336fc3
태블릿, 모바일 뷰
https://github.com/user-attachments/assets/1609d546-60c3-4a83-839e-37e0950ef844

Feat/#64 FAQ 반응형 수정 

---

src/components/Header/Header.tsx
src/pages/FAQ/Question.styled.ts
src/pages/Main/Tracks/InfoBox.tsx
src/pages/Main/index.tsx

> ex) #68
> 2/24 회의 내용 트러블 슈팅 수정 작업
헤더바 '파밍로그' -> '지원하기'로 이름 변경
FAQ 간 간격 조정
홈 네비게이션 바 제거
트랙 소개 파트 트랙 이름 앞에 아이콘 제거

Feat/#68 2/24 회의 내용 트러블 슈팅 수정 작업

---

.github/workflows/deploy.yml

> #71 
> itHub Actions에서 현재 브랜치를 감지하여 TARGET_BRANCH 설정
> develop 브랜치에서는 forked-repo의 develop 브랜치로 동기화
> main 브랜치에서는 forked-repo의 main 브랜치로 동기화
> 기존 ref: main 하드코딩 제거 → 동적으로 브랜치 체크아웃
> GITHUB_ENV를 활용하여 TARGET_BRANCH 변수 설정

chore: GitHub Actions 브랜치별 자동 동기화 로직 수정

---

src/pages/Apply/index.tsx

> #71 
> 배포 자동화가 잘 수정되었는지 확인용 커밋입니다.

test: 배포 자동화 테스트 커밋

---

.github/workflows/deploy.yml
.github/workflows/trigger-fork-sync.yml

> #71 
>  trigger-fork-sync.yml GitHub Actions 실행 → 포크한 저장소(dewbeeny/HomePage-FE)에 repository_dispatch 이벤트 전송하도록 변경

chore:  trigger-fork-sync.yml 파일 추가

---

src/assets/Images/Buttons/ArrowLeft.svg
src/assets/Images/Buttons/ArrowLeftMobile.svg
src/assets/Images/Buttons/ArrowRight.svg
src/assets/Images/Buttons/ArrowRightMobile.svg
src/pages/Main/Achievements/Achievements.styles.ts
src/pages/Main/Achievements/Achievements.tsx

feat: 메인페이지 사진첩 화살표 디자인 및 반응형 완성

---

src/pages/Main/Intro/Intro.styled.tsx
src/pages/Main/Intro/Intro.tsx

> 메인페이지 인트로 섹션 팜소개 추가 전 버전으로 되돌렸습니다.

fix: 인트로 섹션 이전 상태로 되돌리기

---

src/pages/FAQ/Question.styled.ts
src/pages/FAQ/index.styled.ts
src/pages/Main/BottomInfo/BottomInfo.styles.ts

> ex) #85 
> 폰트 오류 문제가 메인 브랜치에 적용 안되어서 다시 커밋합니다.

fix: FAQ 페이지 폰트 적용 문제 수정 - main 브랜치에 적용

---

package-lock.json
package.json
src/Router.tsx
src/pages/Main/index.tsx
src/pages/MaintainPage/MaintainPage.styled.ts
src/pages/MaintainPage/index.tsx

> #92 
> 유지보수 모드(`IS_MAINTENANCE`)가 활성화되면 `MaintainPage`만 표시되도록 변경
> 기존 라우트는 유지보수 모드가 비활성화될 경우 정상적으로 동작하도록 설정

feat: 유지보수 페이지 라우터 설정 추가

---

src/pages/MaintainPage/MaintainPage.styled.ts

style: 백그라운드 색상 변경

---

index.html
public/sitemap.xml

- #81 
- `sitemap.xml` 추가
- 설명, 태그 등 메타데이터 추가
- 구글 서치콘솔 등록용 메타데이터 추가(main에 머지되고 등록 시킬 예정)

feat: SEO를 위해 메타데이터 + sitemap 추가

---

src/Router.tsx
src/components/Header/Header.tsx
src/pages/News/News.styles.ts
src/pages/News/index.tsx

> #104 
> 소식페이지 추가
> 내용이 없을 때 안내 메시지 추가

feat: 소식 페이지 생성 및 등록된 글이 없을 때 안내 메시지 추가

---

.env.example
package-lock.json
package.json
src/config/apiConfig.ts
src/hooks/useApply.ts
src/models/apply.ts
src/pages/Apply/ApplyBox.tsx
src/pages/Apply/ApplyLogin.tsx
src/pages/Apply/ChoiceSelector.tsx
src/pages/Apply/PersonalInfo.tsx
src/pages/Apply/index.tsx
src/services/apply.ts
src/utils/apply.ts
src/validations/apply.ts

- #90 
- 입력값 검증 강화
Zod를 활용하여 PersonalInfo 및 제출 데이터의 유효성을 검증하는 로직을 추가했습니다.
Request, Response 모두 타입스크립트를 통해 타입을 작성했습니다. `models/apply.ts`
- 커스텀훅 제작
`services/apply`에서 axios 통신 로직을 작성 후 `hooks/useApply`에서 커스텀훅으로 만들어 사용성을 높였습니다.
호출 함수, loading, error 스테이터스를 쉽게 관리할 수 있습니다.
- 제출 확인 Alert 추가
제출 버튼 클릭 시 "한번 제출하시면 수정이 불가합니다. 또한 동일한 학번으로 재제출도 불가합니다"라는 경고 메시지를 표시하는 확인 창을 구현했습니다.
제출 시 zod로 한번 전체 질문을 검사하고 싶었지만, zod를 처음써보기도 하고, 어떻게 할지 감이 잘 안잡혀 이부분은 보류했습니다.

feat: 지원하기 페이지 디자인 없이 API 연결 및 관련 기능 구현 + 간단한 동작 화면

---

index.html

> ex) #121 
> 구글 계정으로 ms-clarity 만들고, index.html 태그 코드 적용

feat: index.html <head>태그에 추가

---

src/components/Footer/Footer.tsx
src/pages/Apply/Application/Application.styles.ts
src/pages/Apply/Application/Application.tsx
src/pages/Apply/Step1/Step1.styles.ts
src/pages/Apply/Step1/Step1.tsx
src/pages/Apply/Step2/Step2.styles.ts
src/pages/Apply/Step2/Step2.tsx
src/pages/Main/BottomInfo/BottomInfo.tsx

feat/#127 지원 페이지 오류 수정 

---

package-lock.json
package.json
src/pages/Apply/ApplyBox.tsx

> #133 
>  임시저장 클릭시 지원하기 1 step으로 이동하도록 했습니다.

fix: 임시저장 클릭시 지원하기 1 step으로 이동

---

src/pages/Apply/ApplyBox.tsx

> #133 
> 제출 성공, 임시 저장 성공시 홈화면으로 이동하도록 변경

fix: 제출 성공, 임시 저장 성공시 홈화면으로 이동

---

index.html

> ex) #149 
> 네이버 검색 태그 추가하고 구글SEO 최적화를 위한 한글태그, 영문태그 더 추가했습니다.
네이버 검색하려면 여기 등록을 완료해야합니다. 메인 반영 완료되면 승인 요청 보낼게요~!

feat: 네이버 SEO 추가 + 구글 SEO 최적화

---

.github/workflows/deploy.yml
apps/website/package.json
apps/website/src/Router.tsx
apps/website/src/components/RedirectRoute.tsx
pnpm-lock.yaml

> #159 
> 팜시스템 공식 계정으로 배포 후 관련 설정 변경하였습니다.

Forked Repository Sync: 디벨롭 브랜치 동기화

---

.github/workflows/ci.yml
README.md
turbo.json

fix: ci pnpm으로 변경 + 캐시 적용해보기

---

apps/farminglog/src/pages/auth/SocialRedirect.tsx
packages/api/utils/getClientSideTokens.ts
packages/auth/services/mutation/useSocialLoginPostMutation.ts
packages/auth/stores/useAuthStore.ts

> #186 
> ccessToken을 localStorage 대신 Zustand 상태로 관리하도록 변경했습니다! 이제 다른 api 불러오는 것들 다 가능할거예요~

feat: accessToken을 localStorage 대신 Zustand 상태로 관리하도록 변경

---

apps/farminglog/src/components/Header/Header.styled.ts
apps/farminglog/src/components/Popup/popup.styled.ts
apps/farminglog/src/components/Popup/popup.tsx
apps/farminglog/src/components/Popup/popup.types.ts
apps/farminglog/src/pages/Ranking/index.styles.tsx
apps/farminglog/src/pages/home/Cheer/cheer.styled.ts
apps/farminglog/src/pages/home/Cheer/cheer.tsx
apps/farminglog/src/pages/home/Harvest/harvest.styled.ts
apps/farminglog/src/pages/home/Harvest/harvest.tsx
apps/farminglog/src/pages/home/Ranking/ranking.styled.ts
apps/farminglog/src/pages/home/Ranking/ranking.tsx
apps/farminglog/src/pages/home/index.styled.ts

> ex) #189 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요.

feat : 모달 창 정의 + 홈페이지 메인 화면 반응형 수정

---

apps/farminglog/src/components/Header/Header.styled.ts
apps/farminglog/src/components/Header/Header.tsx
apps/farminglog/src/pages/home/Cheer/cheer.styled.ts
apps/farminglog/src/pages/home/Cheer/cheer.tsx
apps/farminglog/src/pages/home/Harvest/harvest.styled.ts
apps/farminglog/src/pages/home/Harvest/harvest.tsx
apps/farminglog/src/pages/home/Ranking/ranking.styled.ts
apps/farminglog/src/pages/home/Ranking/ranking.tsx
apps/farminglog/src/stores/harvestStore.ts
apps/farminglog/src/utils/convertTagToCategory.ts
packages/auth/stores/userStore.ts

> ex) #201 
> 수정 사항 반영! (안된 부분 : 헤더 fetch해서 업데이트... : 오늘 새벽까지 무조건 할듯 / 홈화면 응원하기 아직 다 못함)

fix : 홈페이지 홈 화면, 헤더 수정 사항 반영

---

apps/farminglog/src/components/Layout.tsx
apps/farminglog/src/pages/cheer/CheerCard.styled.ts
apps/farminglog/src/pages/cheer/CheerCard.tsx
apps/farminglog/src/pages/cheer/index.styled.ts
apps/farminglog/src/pages/cheer/index.tsx
apps/farminglog/src/utils/convertTagToCategory.ts

> #203 
> 응원페이지 일부 수정 및 헤더 상태 유지

feat: 응원페이지 일부 수정 및 헤더 상태 유지

---

packages/auth/stores/userStore.ts

> #208
> 유저 store persist 미들 웨어 제거

fix: 유저 store persist 미들 웨어 제거

---

apps/farminglog/src/services/queryKeys.ts
packages/auth/services/mutation/useLogout.ts

feat: 로그아웃 기능 구현(버튼에 적용 전)

---

packages/auth/hooks/useSocialLogin.tsx

fix: 로그인 로직 일부 수정(도대체 뭐가 바뀐건지 모르겠지만 일단 되는 것 같음)

---

apps/farminglog/src/services/queryKeys.ts
packages/auth/hooks/useSocialLogin.tsx

Reverts DguFarmSystem/HomePage-FE#214

Revert "fix: 로그인 로직 일부 수정(도대체 뭐가 바뀐건지 모르겠지만 일단 되는 것 같음)"

---

apps/farminglog/src/components/Header/Header.styled.ts
apps/farminglog/src/components/Header/Header.tsx
apps/farminglog/src/pages/home/Harvest/harvest.tsx
apps/farminglog/src/pages/home/Ranking/ranking.styled.ts
apps/farminglog/src/pages/home/Ranking/ranking.tsx
apps/farminglog/src/pages/ranking/index.tsx

> ex) #212
> 일일 퀘스트 상태관리 + 헤더 색상 추가 + 임시(모바일 헤더 네이버 바)

fix: 일일 퀘스트 상태관리 + 헤더 색상 추가 + 임시(모바일 헤더 네이버 바)

---

packages/auth/hooks/useSocialLogin.tsx

> #221 
> Google 로그인 URL 누락된 파라미터 추가

fix: Google 로그인 URL 변경

---

apps/farminglog/src/components/Layout.tsx

> #221 
> 레이아웃 주스탠드 user 상태관리 제거

fix: 레이아웃 주스탠드 user 상태관리 제거

---

apps/farminglog/src/pages/auth/SocialRedirect.tsx
apps/farminglog/src/pages/auth/components/StepNotMember.tsx
apps/farminglog/src/stores/useErrorStore.ts
packages/api/hooks/usePublicApi.ts
packages/auth/services/mutation/useSocialLoginPostMutation.ts

> #233 
> 기존 useMutation(mutate) 방식 → mutateAsync + try/catch 로 변경

fix: 로그인 로직 개선

---

apps/farminglog/src/pages/auth/components/StepInputStudentId.tsx
apps/farminglog/src/pages/auth/components/StepNotMember.tsx

> #233 
> 회원이 아닌 사람이 소셜 로그인 시도 했을 때 회원이 아닙니다 뜨고, '처음으로' 버튼 클릭 시에만 step을 'start'로 변경

fix: '처음으로' 버튼 클릭 시에만 step을 'start'로 변경

---

apps/farminglog/src/pages/auth/SocialRedirect.tsx
apps/farminglog/src/stores/useErrorStore.ts

> #233 
> 로그인 에러 메시지 줄바꿈이 안되서 적용

fix: 에러 메시지 줄바꿈 적용

---

apps/farminglog/src/pages/auth/SocialRedirect.tsx
apps/farminglog/src/pages/auth/components/StepStart.tsx
apps/farminglog/src/pages/cheer/write/cheer.tsx
apps/farminglog/src/utils/detect.ts

> #247 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요.

fix: 응원하기, 로그인 로직 1차 QA 반영

---

apps/farminglog/src/pages/auth/components/StepStart.tsx

> #247 
> 실행중인 도메인 가져오도록 다시 변경

fix: 실행중인 도메인 가져오도록 다시 변경

---

apps/farminglog/src/pages/auth/components/StepStart.tsx

fix: 경로 변경

---

apps/farminglog/src/pages/auth/components/StepAuthComplete.tsx
apps/farminglog/src/pages/auth/components/StepStart.tsx

fix: 진짜 마지막 로그인 수정

---

apps/farminglog/src/pages/auth/components/StepAuthComplete.tsx
apps/farminglog/src/pages/auth/components/StepStart.tsx

> #247 
> 인앱 브라우저 탈출시 새로고침으로 로그인 중단되지않게 쿼리 파라미터로체크하도록 수정

fix: 인앱 브라우저 탈출시 새로고침으로 로그인 중단되지않게 쿼리 파라미터로체크하도록 수정

---

apps/farminglog/src/pages/auth/components/StepStart.tsx

fix: 회원인증도 인앱 탈출하도록 수정

---

apps/farminglog/src/pages/myPage/AppView/AppView.styles.tsx
apps/farminglog/src/pages/myPage/AppView/AppView.tsx
apps/farminglog/src/pages/myPage/WebView/WebView.tsx
apps/farminglog/src/utils/convertRoleToString.ts

> ex) #259 
> 마이페이지 웹뷰, 앱뷰 트랙명, 사용자 역할 한글명으로 표시 변경

fix: 마이페이지 웹뷰, 앱뷰 트랙명, 사용자 역할 한글명으로 표시 변경

---

apps/farminglog/src/pages/cheer/write/cheer.tsx
apps/farminglog/src/pages/farminglog/create/index.tsx
apps/farminglog/src/utils/convertUrlsToLinks.tsx

- #265
- [fix: 파밍로그 URL에서 : 생략되는 문제 수정](https://github.com/DguFarmSystem/HomePage-FE/commit/91bad0291031ad1b28d45201ec9410520ccb6bae)
- [hotfix: 전송완료 모달에서 엔터/스페이스 바 입력시 요청 전송 문제 해결](https://github.com/DguFarmSystem/HomePage-FE/commit/44c7c44abf2d225e96f83784ac72070417e8d014) 
- 전송 버튼에 포커스 잡혔어서 생기는 문제같습니다. 팝업이 열리는 동안 버튼들을 disable 해서 해결했습니다.
- [ x] UI/UX 디자인 적용 확인

hotfix: 파밍로그 링크 깨짐 수정 + 엔터키 요청 고치기 #265

---

apps/farminglog/src/components/Header/Header.styled.ts
apps/farminglog/src/components/Popup/popup.styled.ts
apps/farminglog/src/components/Popup/popup.tsx
apps/farminglog/src/layouts/WhiteContentContainer.styled.ts
apps/farminglog/src/pages/farminglog/create/index.styled.ts
apps/farminglog/src/pages/farminglog/view/index.styled.ts
apps/farminglog/src/pages/home/Ranking/ranking.styled.ts
apps/farminglog/src/pages/ranking/index.styles.tsx

> ex) #275 
> 자잘한 UI 수정사항 변경작업

Feature/#275 자잘한 UI 수정사항 변경작업

---

apps/website/src/components/Header/Header.tsx

[Fix] 블로그/프로젝트 모바일 헤더 네비게이션 바 수정 

---

.github/workflows/deploy.yml

> #292 
> 이번 PR에서 작업한 내용을 간략히 설명해주세요.

deploy: dev 페이지 배포 오류로 인해 업로드

---

.github/workflows/deploy.yml

> ex) #292 
> ci/cd시 계속 권한오류가 발생하네요...

fix: ci/cd코드 수정

---

apps/website/package.json
apps/website/vercel.json

> #295 
> dist폴더 못찾는 문제 => 명시 진행
> vercel build 시 오류 수정

fix: vercel missing_directory오류

---

apps/website/api/og.js
apps/website/src/hooks/useLinkPreview.ts

> #294 
> serverless 함수 동작 확인 및 tag 데이터가 null 시, 카드 아이템 컴포넌트에서 처리

fix: 동적 렌더링 구현 및 커스텀 훅 null 처리

---

apps/website/vercel.json
package.json
pnpm-lock.yaml

> ex) #295 
> 종속성 오류 및 vercel.json 수정

fix: 종속성 업데이트 및 vercel.json 수정

---

apps/website/vercel.json

> #292 
> vercel.json 파일 형식 오류로 인한 픽스

fix: vercel.json 작성 형식 수정

---

apps/website/src/hooks/useLinkPreview.ts
apps/website/src/pages/Blog/Blog/BlogItem.tsx
apps/website/src/pages/Blog/Blog/BlogList.tsx
apps/website/src/stores/useLinkPreviewStore.ts

> ex) #304 
> 1. zustand Link preview
> 2. 로드 시 3개 씩 preview 로딩

[Fix] 블로그 로딩 시 캐시 적용 및 로딩 3개 씩 순차대로

---

apps/farminglog/src/components/UnityWebGL/UnityWebGL.tsx
apps/farminglog/src/pages/UnityGame/index.styled.ts
apps/farminglog/src/pages/game/index.tsx

> ex) #306
> 이번 PR에서 작업한 내용을 간략히 설명해주세요.

[Fix] 게임 화면 사이트 사이즈 늘리기

---

apps/website/src/pages/Blog/Blog/BlogItem.tsx
apps/website/src/pages/Blog/Blog/BlogList.tsx

> ex) #310 
> 태그 소문자로 인식해서 오류 발생한 것 고쳤습니다.

[HotFix] 블로그 태그 핫픽스

---

apps/website/src/models/blog.ts
apps/website/src/pages/Blog/Blog/BlogList.tsx
apps/website/src/services/blog.ts

[HotFix] 블로그 통신모델 핫픽스

---

apps/website/src/services/blog.ts

> ex) #317 
> 배포 시와 개발 시의 데이터 모델이 왜 다른지 모르겠지만 달라서  유동적으로 할 수 있도록 변경

[Hotfix] prod와 dev가 왜 다를까???ㅠㅠㅠ
